info.emp.eid= 10
info.emp.ename = nikhil
info.emp.eage =19.9
info.emp.friends = sachin,kunal,kartik,pankaj
info.emp.number = 7011752235,9810667877,9560861912
info.emp.accountNumber = {sbi:'12335',canra:'454778'}
